### ISSUE TITLE
`memory_limit` option is not properly validate when passed via `MemoryOptions::__construct` or set via `MemoryOptions#setMemoryLimit`

### ISSUE THREAD

**Issue by leuchtdiode** [laminas/laminas-cache-storage-adapter-memory#54]
Hi,

I'm debugging why my given memory limit is not being applied in the adapter. Looks like there is a bug in the MemoryOptions. I think `preg_match` in this line

https://github.com/laminas/laminas-cache-storage-adapter-memory/blob/d2c357a8b839ceb0e0781d5e9aebe46642dbf0b2/src/MemoryOptions.php#L88

should use the parameter `$value` instead of `ini_get('memory_limit')`?

BR,
Alex

**Comment by Ocramius** [comment]
> I'm debugging why my given memory limit is not being applied in the adapter.

Would you be able to write a small integration test using `ini_set()` and `@runInSeparateProcess`, perhaps?

**Comment by leuchtdiode** [comment]
> > I'm debugging why my given memory limit is not being applied in the adapter.
> 
> Would you be able to write a small integration test using `ini_set()` and `@runInSeparateProcess`, perhaps?

I will try to find some time the next days to write some tests.

**Comment by Xerkus** [comment]
Introduced in time immaterial by https://github.com/laminas/laminas-cache-storage-adapter-memory/commit/b87cc7469eedc691138142e55a1c20c16cf49221

There are no tests whatsoever for options object. 
@leuchtdiode It would be great if you introduce them.

For this problem ini_set/ini_get is not needed. Test that:
- call to `setMemoryLimit()` with invalid value like `'M128'` produces exception with message containing "Invalid memory limit".
- call to `setMemoryLimit()` actually sets it.

**Comment by leuchtdiode** [comment]
I just created a pull request, but there are some issues with my formatting. Do you have a code style XML somewhere for PHPStorm which I can use?

Furthermore I added these tests:

`[ 'M256', 256 ]
[ 'G1024', 1024 ]`

as valid ones. In my opinion they should raise an InvalidArgumentException as well. What do you think? Which values do we want to allow? Only integers and "G", "M" and "k" as suffix, right? If so, I could adapt the regex and the tests.

Also I added to return "null" when "null" is given to normalize, because it broke the already existing test `testOptionsFluentInterface` from the common base test class.

**Comment by Ocramius** [comment]
> Do you have a code style XML somewhere for PHPStorm which I can use?

There's a PHPCS configuration at the root of the repository:  https://github.com/laminas/laminas-cache-storage-adapter-memory/blob/d2c357a8b839ceb0e0781d5e9aebe46642dbf0b2/phpcs.xml#L1-L20

 > as valid ones. In my opinion they should raise an InvalidArgumentException as well. What do you think? Which values do we want to allow? Only integers and "G", "M" and "k" as suffix, right? If so, I could adapt the regex and the tests.

Worth discussing on the PR directly :)
