### ISSUE TITLE
[RFC]: Serialize objects

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-cache-storage-adapter-memory#63]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 3.0.0  |
| BC Break?           | Maybe |

### Goal

Make objects immutable when written to cache.

### Background

There are integration tests which verify that objects written to caches are not modified when reading from cache.

```php

$object = new stdClass;
$object->foo = 'bar';

$cache->setItem('foo', $object);
$object->foo = 'baz';

$objectFromCache = $cache->getItem('foo');

assert($objectFromCache->foo === 'bar');
```

This test is failing for memory adapter as memory adapter stores references. Other caches are serializing objects with several serializers which could be adapted in the memory adapter as well.

### Considerations

Users can pass an optional serializer option to the `MemoryOptions`.

### Proposal(s)

Allow serializer option for `Memory` adapter in the same way we allow for i.e. the `Redis` adapter.
By default, we can use `serialize` from PHP. 

### Appendix

Ref: [symfony/cache ArrayAdapter](https://github.com/symfony/symfony/blob/8f71c8db4c4dc12134b2fc74e5efc5171993285c/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php#L44)
Ref: [failing cache integration test](https://github.com/laminas/laminas-cache-storage-adapter-test/blob/20f81115336b7de59eddd2932ab04623a8000096/src/AbstractSimpleCacheIntegrationTest.php#L731)

**Comment by gsteel** [comment]
Makes perfect sense to me…

Are you suggesting a serializer instance as the option value, meaning, no serialization occurs unless a serializer is given, or doing the same thing as Symfony with just an on/off switch in config and using built-in `serialize` from PHP?

**Comment by boesing** [comment]
guess I will just allow plugins in general and this will allow the serializer plugin which can then opted in. if an object is passed, another option (like boolean serialize) could be added to serialize objects even without having the plugin added. but maybe having the plugin is already good enough. 

exit: oh wait all adapters allow plugins, so if s1 needs objects to be immutable, using the serializer plugin would already work. 

Guess I close this RFC as I do not see a need anymore 🤔
